"""DomainPack facade of the known-ground-truth synthetic causal fixture.

The recipe, runner programs and estimator equal the legacy
``synthetic_causal`` and ``synthetic_batch_analysis`` modules, which stay
unchanged for legacy bindings and replay. The hidden world lives only in
``protocol.data``; analysis hooks receive a CasView without it. Generated
observations are fixtures, not evidence about a real population, and the
reanalysis is a distinct calculation on the same observations.
"""

import hashlib

from episteme.domains import api

from . import analysis, compiler, programs


PACK_ID = compiler.DOMAIN_ID
PACK_VERSION = "1"
NUMERIC_TOLERANCE = 1e-9  # Absolute arithmetic agreement, not scientific uncertainty.
WALL_SECONDS = 120
MAX_OUTPUT_BYTES = 1024 * 1024

MANIFEST = {
    "contract_version": 1, "pack_id": PACK_ID, "pack_version": PACK_VERSION,
    "description": "Known-ground-truth synthetic causal fixture; estimates are descriptive.",
    "roster_semantics": ["rng_seed"],
    "metrics": [{"name": compiler.METRIC, "unit": "outcome units",
                 "description": "Treatment contrast of one generated synthetic sample"}],
    "outputs": {"raw_data": {"path": "raw.json", "schema_id": "synthetic_causal_v1/raw-v1"},
                "metrics": {"path": "metrics.json", "schema_id": "synthetic_causal_v1/metrics-v1"}},
    "numeric_tolerance": NUMERIC_TOLERANCE,
    "hidden_inputs": ["protocol_data"],
    "execution_profiles": ["trusted_local_python_v1"],
    "statistical_capabilities": ["estimand", "estimator", "point_estimate", "sample_size",
                                 "stopping_rule", "sensitivity_analysis", "deviations"],
    "interpretation_cautions": [
        "All observations were generated by a synthetic fixture, not collected from a real population.",
        "The separate reanalysis uses the same observations; it is not new-data replication.",
        "Different RNG seeds repeat one generator and one estimator; they do not test another design.",
    ],
    "capture": False,
}

_ESTIMATORS = {
    "difference_in_means": "Mean outcome of treated minus untreated synthetic units.",
    "adjusted_ols": "Treatment coefficient of OLS Y ~ 1 + T + U from weighted within-U contrasts.",
}


def describe():
    return api.ParameterCatalog(
        schema_version=1, pack_id=PACK_ID, pack_version=PACK_VERSION,
        description="Known-ground-truth synthetic causal fixture; estimates are descriptive.",
        parameters_schema=compiler.PARAMETERS_SCHEMA, metric=compiler.METRIC,
        outputs=dict(compiler.OUTPUTS), limitations=list(compiler.LIMITATIONS))


def validate_parameters(parameters):
    compiler.parameters(api.thaw(parameters))


def _compiled(request):
    chosen = compiler.parameters(api.thaw(request.parameters))
    world, seeds, tolerance = compiler.host(api.thaw(request.host_inputs))
    if request.capture is not None:
        raise ValueError("synthetic causal pack takes no captured source")
    return chosen, seeds, tolerance, compiler.data(chosen, world)


def compile_protocol(request):
    chosen, seeds, tolerance, data = _compiled(request)
    design, analysis_plan, stopping_rule, statistical_design = compiler.protocol_texts(chosen, data)
    return api.ProtocolDraft(
        schema_version=1, design=design, analysis_plan=analysis_plan, metric=compiler.METRIC,
        stopping_rule=stopping_rule, statistical_design=statistical_design, roster=seeds,
        roster_semantics="rng_seed", sample_size_scope="per_roster_unit",
        run_limit=2 * len(seeds), replication_tolerance=tolerance, seen_data=[])


def compile_execution(request):
    _, _, _, data = _compiled(request)
    return api.ExecutionPlan(
        primary_program=programs.PRIMARY_SOURCE, reanalysis_program=programs.REANALYSIS_SOURCE,
        input=data, outputs=dict(compiler.OUTPUTS), wall_seconds=WALL_SECONDS,
        max_output_bytes=MAX_OUTPUT_BYTES, required_capabilities=[],
        execution_profile="trusted_local_python_v1",
        environment_requirements=api.environment_requirements())


def validate_protocol(context):
    protocol = context.protocol
    splits = protocol["statistical_design"]["data_splits"]
    if (protocol["metric"] != compiler.METRIC or protocol.get("protocol_mode") != "exploratory"
            or protocol["data"] != context.execution_plan["input"]["sha256"]
            or list(protocol["seeds"]) != list(context.draft.roster)
            or len(splits) != 1 or splits[0]["digest"] != protocol["data"]
            or (splits[0]["role"], splits[0]["exposure_policy"]) != ("discovery", "open")):
        raise ValueError("synthetic protocol differs from its exploratory generator recipe")


def validate_outputs(context, cas):
    frozen = api.thaw(context.parameters)
    checks = []
    for row in context.slots:
        findings = []
        try:
            if row["mode"] == "primary":
                _, observed = analysis.raw(cas, row["outputs"]["raw_data"], seed=row["roster_unit"])
                if observed != frozen:
                    raise ValueError("observed synthetic parameters differ from the frozen experiment recipe")
            else:
                primary = context.slot(f"primary:{row['roster_unit']}")
                if primary["outputs"]["raw_data"] != row["outputs"]["raw_data"]:
                    raise ValueError("reanalysis did not use the primary observations")
            analysis.metric(cas, row["outputs"]["metrics"])
        except ValueError as exc:
            findings.append(str(exc))
        checks.append(api.OutputCheck(
            schema_version=1, slot=row["slot"], roster_unit=row["roster_unit"], mode=row["mode"],
            result=row["result"], raw_data=row["outputs"]["raw_data"],
            metrics=row["outputs"]["metrics"], status="failed" if findings else "passed",
            findings=findings))
    return checks


def _seed_rows(context, cas, seed):
    primary = context.slot(f"primary:{seed}")
    reanalysis = context.slot(f"reanalysis:{seed}")
    if reanalysis["outputs"]["raw_data"] != primary["outputs"]["raw_data"]:
        raise ValueError("reanalysis did not use the primary observations")
    rows, observed = analysis.raw(cas, primary["outputs"]["raw_data"], seed=seed)
    if observed != api.thaw(context.parameters):
        raise ValueError("observed synthetic parameters differ from the frozen experiment recipe")
    return primary, reanalysis, rows, observed


def recompute_metrics(context, cas):
    result = []
    for seed in context.draft.roster:
        primary, reanalysis, rows, observed = _seed_rows(context, cas, seed)
        recomputed = analysis.estimate(rows, observed["analysis"])
        reported_primary = analysis.metric(cas, primary["outputs"]["metrics"])
        reported_reanalysis = analysis.metric(cas, reanalysis["outputs"]["metrics"])
        primary_delta = abs(recomputed - reported_primary)
        reanalysis_delta = abs(recomputed - reported_reanalysis)
        if primary_delta > context.numeric_tolerance or reanalysis_delta > context.numeric_tolerance:
            raise ValueError(f"synthetic metric disagrees with recomputed raw data for seed {seed}")
        result.append(api.Recomputation(
            schema_version=1, roster_unit=seed, metric=compiler.METRIC, recomputed=recomputed,
            primary_recorded=reported_primary, reanalysis_recorded=reported_reanalysis,
            primary_absolute_difference=primary_delta,
            reanalysis_absolute_difference=reanalysis_delta, tolerance=context.numeric_tolerance))
    return result


def analyse(context, cas, checks, recomputations):
    failed = [check for check in checks if check.status != "passed"]
    if failed:
        raise ValueError("synthetic outputs failed pack checks: "
                         + "; ".join(item for check in failed for item in check.findings))
    by_seed = {row.roster_unit: row for row in recomputations}
    if sorted(by_seed) != sorted(context.draft.roster):
        raise ValueError("synthetic recomputations do not cover the registered seeds")
    design = context.draft.typed_design()
    chosen = api.thaw(context.parameters)
    details = []
    for seed in context.draft.roster:
        primary, reanalysis, rows, _ = _seed_rows(context, cas, seed)
        row = by_seed[seed]
        details.append(dict(seed=seed, primary_run=primary["run"], primary_result=primary["result"],
                            reanalysis_run=reanalysis["run"], reanalysis_result=reanalysis["result"],
                            raw_data=primary["outputs"]["raw_data"], n_units=len(rows),
                            n_treated=sum(item["t"] for item in rows),
                            n_control=sum(item["t"] == 0 for item in rows),
                            recomputed_treatment_effect=row.recomputed,
                            primary_reported_treatment_effect=row.primary_recorded,
                            reanalysis_reported_treatment_effect=row.reanalysis_recorded,
                            primary_absolute_difference=row.primary_absolute_difference,
                            reanalysis_absolute_difference=row.reanalysis_absolute_difference))
    rendered = ", ".join(f"seed {item['seed']}: {item['recomputed_treatment_effect']:.12g}"
                         for item in details)
    analysed = sum(item["n_units"] for item in details)
    report = api.StatisticalReport.from_dict({
        "schema_version": 1, "protocol_hash": context.protocol_hash,
        "estimand": api.supplied({"protocol_hash": context.protocol_hash, "text": design.estimand}),
        "estimator": api.supplied({"name": chosen["analysis"], "hook": "recompute_metrics",
                                   "description": _ESTIMATORS[chosen["analysis"]]}),
        "point_estimate": api.supplied({
            "metric": compiler.METRIC, "unit": design.primary_metric.unit, "value": None,
            "by_roster_unit": [{"roster_unit": item["seed"],
                                "value": item["recomputed_treatment_effect"]} for item in details]}),
        "uncertainty": api.not_applicable(
            "Preregistered uncertainty.method is not_applicable; point estimates only."),
        "confidence_interval": api.not_applicable(
            "Preregistered uncertainty.method is not_applicable; no interval is computed."),
        "effect_size": api.not_supplied(
            "Per-seed unstandardized contrasts are the point estimates; no pooled or standardized "
            "effect size is computed by this pack."),
        "assumptions": api.not_supplied(
            "Balance, positivity and correct adjustment are not checked by this pack."),
        "sample_size": api.supplied({
            "experimental_unit": design.experimental_unit, "unit_scope": "per_roster_unit",
            "planned": design.sample_size,
            "planned_total": design.sample_size * len(context.draft.roster),
            "analysed": analysed, "exclusions": [], "missing_slots": []}),
        "multiple_testing": api.not_applicable(
            "No significance tests or hypothesis family were preregistered."),
        "stopping_rule": api.supplied({
            "rule_sha256": hashlib.sha256(design.stopping_rule.rule.encode("utf-8")).hexdigest(),
            "roster_complete": True, "interim_looks": 0}),
        "sensitivity_analysis": api.supplied([]),
        "deviations": api.supplied([]),
    })
    return api.AnalysisReport(
        pack_id=PACK_ID, pack_version=PACK_VERSION, protocol_hash=context.protocol_hash,
        statement=("Synthetic causal fixture treatment_effect point estimates from "
                   f"all registered observations were {rendered}. These exploratory "
                   "descriptions do not establish a causal or real-world finding."),
        limitations=[
            "All observations were generated by a synthetic fixture, not collected from a real population.",
            "The separate reanalysis uses the same observations; it is not new-data replication.",
            "No uncertainty interval, power analysis, significance test or scientific review is supplied.",
        ],
        outcome="inconclusive", inference_mode="exploratory",
        details=dict(domain=PACK_ID, assignment=chosen["assignment"], analysis=chosen["analysis"],
                     metric=compiler.METRIC, absolute_numeric_tolerance=context.numeric_tolerance,
                     seed_results=details),
        statistical_report=report)
